### ISSUE TITLE
onClick fires for every item

### ISSUE THREAD

**Issue by BGMcoder** [freaktechnik/jetpack-panelview#24]
I have set up panelview on an sdk action-button using the example in the tutorial.  When I click on the action-button it fires EVERY onclick event of the panelview's menu items.  If I click one of the panelview's menu items, it fires EVERY onclick event of every panelview menu item!

So it seems like something is wrong.  All the menu items in the panelview (using the example) always fire on any onClick panelview event.

**Comment by freaktechnik** [comment]
That sounds weird. Of course I cannot reproduce it. The onClick of every node is only added as a listener for that node and no other node. Does it also fire the onClick for the footer? Because if it is consistent, it will.

Just for completion's sake: which Firefox version and on which OS are you trying this?

**Comment by BGMcoder** [comment]
Thanks for answering.

Here is my code page:
http://p.ahkscript.org/?p=71f3f58a

I'm running Windows 7x64 Pro and the latest Firefox 
Developer Version.

**Comment by freaktechnik** [comment]
Interstingly enough I was able to reproduce this on a different computer with nightly both with a similar scenario you used and in the event listener unit test.

**Comment by BGMcoder** [comment]
Wow!  That's a rare case!  Thanks for taking the time.  I'm sorry for you, though!

**Comment by freaktechnik** [comment]
Okay, I've published 0.2.3, which fixes the issue for me. It seems to be related to e10s shims the SDK introduced.

**Comment by BGMcoder** [comment]
That works!  Thanks a lot!
